name: my workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo "my first workflow"
            - name: list a file
              run: ls
            - name: read file
              run: cat README.md

            