name: Generate ASCII value

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4

            - name: list file repo
              run: ls -lrt
              
            - name: Executing shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

            